# Generated by Django 3.0.5 on 2020-04-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item", name="text", field=models.TextField(default=""),
        ),
    ]
